spring:
  application:
    name: it-day-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/it_day_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    #jdbc:mysql://localhost:3306/it_day_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${IT_DAY_DB_USERNAME}
    password: ${IT_DAY_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

jwt:
  token:
    secretKey: ${JWT_SECRET}
    expiration:
      access: ${JWT_ACCESS_EXPIRATION:1h}
      refresh: ${JWT_REFRESH_EXPIRATION:14d}

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  client-id: ${KAKAO_CLIENT_ID:}
  redirect-uri: ${KAKAO_REDIRECT_URI:}
  client-secret: ${KAKAO_CLIENT_SECRET:}
  admin-key: ${KAKAO_ADMIN_KEY:}

toss:
  secret-key: ${TOSS_SECRET_KEY:test_sk_dummy}
  client-key: ${TOSS_CLIENT_KEY:test_ck_dummy}

frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
